name: "check-build"
on:
  push:
    branches:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required libraries
        run: sudo apt-get install -y libogg-dev libvorbis-dev catch2

      - name: Configure build directory structure
        run: mkdir -p build/bin

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test with Catch2
        run: cd build/bin && ./tests
