name: "check-build"
on:
  push:
    branches:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required libraries
        run: sudo apt-get install -y libogg-dev libvorbis-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cd build/ && make

      # TODO: Add CTest for testing
